### ISSUE TITLE
Thiết kế cách xác định đúng sai khi đưa package vào drop zone

### ISSUE THREAD

**Issue by bananeee** [bananeee/CNPM-project#4]
T nghĩ nên để package là object với 1 thuộc tính là id hoặc boolean week day. Nếu ô có cách triển khai tốt hơn thì cứ thực hiện nhé

**Comment by namedai01** [comment]
Cách 2: Có thể thử cách chèn cái Image vào cái vùng Zone rồi rồi xử lý va chạm giữa 2 image. Tuy nhiên cần phải tìm hiểu thêm sự kiện va chạm của Phaser có những gì.
