### ISSUE TITLE
Thêm asset project 2

### ISSUE THREAD

**Issue by bananeee** [bananeee/CNPM-project#6]
Thêm các khung hình ảnh để lựa chọn, 2 button sáng chiều

**Comment by gnol-pham** [comment]
[Lesson2.zip](https://github.com/bananeee/CNPM-project/files/4492461/Lesson2.zip)

**Comment by gnol-pham** [comment]
[Lesson2.zip](https://github.com/bananeee/CNPM-project/files/4494403/Lesson2.zip)
